  <div id="myCarousel" class="carousel slide">
	      <div class="carousel-inner">
	        <div class="item active">
	          <img src="{{ site.baseurl }}/img/VinterRoros.jpg" alt="First slide">
	          <div class="container">
	            <div class="carousel-caption">
	              <h1>Skapt for et langt og hardt liv</h1>
	            </div>
	          </div>
	        </div>
	        <div class="item">
	          <img src="{{ site.baseurl }}/img/hytte.jpg" alt="Second slide">
	          <div class="container">
	            <div class="carousel-caption">
	              <h1>Det originale hyttevinduet</h1>
	            </div>
	          </div>
	        </div>
	        <div class="item">
	          <img src="{{ site.url }}/img/kids.jpg" alt="Third slide">
	          <div class="container">
	            <div class="carousel-caption">
	              <h1>Godt inneklima</h1>
	            </div>
	          </div>
	        </div>
	      </div>
	      <a class="left carousel-control" href="#myCarousel" data-slide="prev"><span class="glyphicon glyphicon-chevron-left"></span></a>
	      <a class="right carousel-control" href="#myCarousel" data-slide="next"><span class="glyphicon glyphicon-chevron-right"></span></a>
		</div><!-- carousel -->
