		<footer>
		<div class="container">
			<div class="col-sm-6 col-md-4">
				<ul>
					<li><h4>Vinduer</h4></li>
					<li><a href="#">Lala</a></li>
					<li><a href="#">Lolo</a></li>
				</ul>
			</div>
			<div class="col-sm-6 col-md-4">
				<ul>
					<li><h4>Dører</h4></li>
					<li><a href="#">Lala</a></li>
					<li><a href="#">Lolo</a></li>
				</ul>
			</div>
			<div class="col-sm-6 col-md-4">
				<ul>
					<li><h4>Kontakt</h4></li>
					<li>7374 Røros<br />
						Tlf.: 72 40 63 00<br />
						Fax: 72 40 62 91<br />
						E-mail: <a href="#" class="mail">ordre.roros@roros-bruk.no</a><br /><br />
						Ring eller send oss en mail hvis du vil ha tilsendt brosjyre, prisliste og/eller monteringsanvisning.</li>
				</ul>
			</div>
			</div><!-- container end -->
			<div class="stichline whiteline"></div><p class="copyright">&copy; 2013 - <a href="http://isola.no">Isola AS</a></p>
		</footer>
		
		 
		
  	
  
    

    <!-- jQuery (necessary for Bootstrap's JavaScript plugins) -->
    <script src="//code.jquery.com/jquery.js"></script>
    <!-- Include all compiled plugins (below), or include individual files as needed -->
    <script src="{{ site.url }}js/bootstrap.min.js"></script>
	<script src="{{ site.url }}js/flowtype.js"></script>
    <script src="{{ site.url }}js/admin.js"></script>
    
    	  
   
  
  </body>
</html>