<!DOCTYPE html>
<html>
  <head>
    <title>{{ page.title }}</title>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta charset="utf-8"> 
    <!-- Bootstrap -->
    <link href="{{ site.baseurl }}/css/bootstrap.css" rel="stylesheet" media="screen">
    
    <!-- Custom styling -->
    <link href='http://fonts.googleapis.com/css?family=Ropa+Sans' rel='stylesheet' type='text/css'>
    <link href="{{ site.baseurl }}/css/global.css" rel="stylesheet" media="screen">

    <!-- HTML5 shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!--[if lt IE 9]>
      <script src="../../assets/js/html5shiv.js"></script>
      <script src="../../assets/js/respond.min.js"></script>
    <![endif]-->
  </head>
  <body>