<div class="navWrap"><nav id="Nav" class="navbar navbar-default affix-top" role="navigation">
		  <!-- Brand and toggle get grouped for better mobile display -->
		  <div class="navbar-header">
		    <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-ex1-collapse">
		      <span class="sr-only">Toggle navigation</span>
		      <span class="icon-bar"></span>
		      <span class="icon-bar"></span>
		      <span class="icon-bar"></span>
		    </button>
		  </div>
		
		  <!-- Collect the nav links, forms, and other content for toggling -->
		  <div class="collapse navbar-collapse navbar-ex1-collapse">
		    <div class="container navInner">
		    
		    <ul class="nav nav-justified mainNav">
		    
		    <li><a href="{{ site.baseurl }}/">Forsiden</a></li>
		    
		      <li class="dropdown">
		        <a href="{{ site.baseurl }}/vinduer" class="dropdown-toggle disabled" data-toggle="dropdown">Vinduer <b class="caret"></b></a>
		        <ul class="dropdown-menu">
		          <li><a href="#">Røros Original Koblet</a></li>
		          <li><a href="{{ site.baseurl }}/vinduer/isoler">Røros Vinduet Isoler</a></li>
		          <li><a href="#">Hvordan velge vindu</a></li>
		        </ul>
		      </li>
		      
		      <li class="dropdown">
		        <a href="#" class="dropdown-toggle" data-toggle="dropdown">Dører <b class="caret"></b></a>
		        <ul class="dropdown-menu">
		          <li><a href="#">Speildører</a></li>
		          <li><a href="#">Paneldører</a></li>
		          <li><a href="#">Terrassedører</a></li>
		        </ul>
		      </li>
		      
		      <li class="dropdown">
		        <a href="#" class="dropdown-toggle" data-toggle="dropdown">Om oss <b class="caret"></b></a>
		        <ul class="dropdown-menu">
		          <li><a href="{{ site.baseurl }}/om-oss/historien">Historien</a></li>
		          <li><a href="#">Salg og produksjon</a></li>
		          <li><a href="#">Ledige stillinger</a></li>
		          <li><a href="#">Rørs miljø og kvalitet</a></li>
		        </ul>
		      </li>
		      
		      <li class="dropdown">
		        <a href="#" class="dropdown-toggle" data-toggle="dropdown">Kundeservice <b class="caret"></b></a>
		        <ul class="dropdown-menu">
		          <li><a href="{{ site.baseurl }}/kundeservice/kontakt">Kontaktinfo/ordrekontor og service</a></li>
		          <li><a href="{{ site.baseurl }}/kundeservice/reklamasjoner">Reklamasjoner/Serviceskjema</a></li>
		          <li><a href="#">Ofte stilte spørsmål/servicehåndbok</a></li>
		          <li><a href="#">Salgs- og leveringsbetingelser</a></li>
		        </ul>
		      </li>
		    
		    
		    </ul></div><div class="stichline"></div>
		  </div><!-- /.navbar-collapse -->
		</nav>
		</div><!-- container end -->
</div>