{% if page.title == "Vinduer" %}
				<aside class="col-sm-12 col-md-3">
					<ul>
						<li><a href="#">Vinduer</a></li>
						<li><a href="#">Røros Original Koblet</a></li>
						<li><a href="#" class="activeAside">Røros Isoler</a></li>
					</ul>
				</aside>
{% endif %}
{% if page.title == "Vinduer - Isoler" %}
				<aside class="col-sm-12 col-md-3">
					<ul>
						<li><a href="#">Vinduer</a></li>
						<li><a href="#">Røros Original Koblet</a></li>
						<li><a href="#" class="activeAside">Røros Isoler</a></li>
							<ul>
								<li><a href="#">Sidehengslet/Topphengslet</a></li>
								<li><a href="#">Toppsving</a></li>
								<li><a href="#">Sidesving</a></li>
								<li><a href="#">Fastkarm</a></li>
							</ul>
					</ul>
				</aside>
{% endif %}
{% if page.title == 'om-oss' %}
				<aside class="col-sm-12 col-md-3">
					<ul>
						<li><a href="#">Kundeservice</a></li>
						<li><a href="#" class="activeAside">Kontaktinfo / ordrekontor og service</a></li>
						<li><a href="#">Reklamasjoner / Natre skjema</a></li>
						<li><a href="#">Ofte stilte spørsmål / servicehåndbok</a></li>
						<li><a href="#">Salgs- og leveringsbetingelser</a></li>
					</ul>
				</aside>
{% endif %}
{% if page.title == 'Kundeservice - Kontakt' %}

				<aside class="col-sm-12 col-md-3">
					<ul>
						<li><a href="#">Om oss</a></li>
						<li><a href="#" class="activeAside">Historien</a></li>
						<li><a href="#">Salg og produksjon</a></li>
						<li><a href="#">Ledige stillinger</a></li>
						<li><a href="#">Røros miljø og kvalitet</a></li>
					</ul>
				</aside>
				
{% endif %}